### ISSUE TITLE
Incorporate into dependable-ai/nn-dependability-kit

### ISSUE THREAD

**Issue by impredicative** [darioizzo/neurostability#2]
Is it possible to have this code and technique properly incorporated into https://github.com/dependable-ai/nn-dependability-kit ? It's much better to have it in one toolbox. This repo can still independently exist, of course. The cross-posted issue is [this](https://github.com/dependable-ai/nn-dependability-kit/issues/26). Thanks.

**Comment by darioizzo** [comment]
I am not familiar with dependable-ai/nn-dependability-kit, but in principle the methodology we introduce in the paper (e.g. linearize the system dynamics to study globally the system behavior next to a equilibria, or expand onto high order Taylor series using differential algebra to study a single nominal trajectory) can indeed be applied rather generically.
